kubectl taint node i-0c39eb81216774c40 high-cpu=yes:NoSchedule
kubectl taint node i-03febc93867c8dae6 med-cpu=yes:NoSchedule
kubectl taint node i-02f25ad93412e6272 low-cpu=yes:NoSchedule

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - image: nginx:latest
          name: nginx
      tolerations:
        - key: "high-cpu"
          operator: "Equal"
          value: "yes"
          effect: "NoExecute"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app2
  name: app2
  spec:
    replicas: 6
    selector:
      matchLabels:
        app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - image: nginx:latest
          name: nginx
      tolerations:
        - key: "med-cpu"
          operator: "Equal"
          value: "yes"
          effect: "NoExecute"
        - key: "low-cpu"
          operator: "Equal"
          value: "yes"
          effect: "NoExecute"
